# 名称
name: Push Docker Image to Alibaba Cloud

on:
 # 出发的动作
  push:
    branches:
      - main  # 触发工作流的分支

env:
  ALICLOUD_REGISTRY: "${{ secrets.ALICLOUD_REGISTRY }}"
  ALICLOUD_NAME_SPACE: "${{ secrets.ALICLOUD_NAME_SPACE }}"
  ALICLOUD_USERNAME: "${{ secrets.ALICLOUD_USERNAME }}"
  ALICLOUD_PASSWORD: "${{ secrets.ALICLOUD_PASSWORD }}"
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Alibaba Cloud Docker Registry
        run: |
          echo $ALICLOUD_PASSWORD | docker login --username=$ALICLOUD_USERNAME $ALICLOUD_REGISTRY --password-stdin
      - name: Load configuration
        id: load-config
        run: |
          source config.env
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        shell: bash

      - name: Pull Docker image from Docker Hub
        run: |
          docker pull ${REPO_NAME}:${IMAGE_TAG}

      - name: Tag Docker image for Alibaba Cloud
        run: |
          docker tag $ALICLOUD_REGISTRY/$ALICLOUD_NAME_SPACE/${REPO_NAME}:${IMAGE_TAG}



      - name: Push Docker image to Alibaba Cloud
        run: |
          docker push $ALICLOUD_REGISTRY/$ALICLOUD_NAME_SPACE/${REPO_NAME}:${IMAGE_TAG}

      - name: Logout from Docker registry
        run: docker logout $ALIYUN_REGISTRY
